"""Manifest of files generated by a cxbind run: .cxbind/manifest.txt.

Tools like cxtest read it to know exactly what was generated, wherever the
targets put their files. One path per line, relative to the project
directory (the parent of .cxbind), forward slashes. That file format is the
contract; this class is just the convenient way to read and write it.
"""

from pathlib import Path

MANIFEST_NAME = "manifest.txt"


class Manifest:
    def __init__(self, state_dir: Path | str = "_cxbind") -> None:
        self.state_dir = Path(state_dir)

    @property
    def project_dir(self) -> Path:
        return self.state_dir.parent

    @property
    def path(self) -> Path:
        return self.state_dir / MANIFEST_NAME

    def exists(self) -> bool:
        return self.path.exists()

    def reset(self) -> None:
        """Start fresh; call once at the start of a run so stale outputs don't linger."""
        self.path.unlink(missing_ok=True)

    def record(self, output: Path | str) -> None:
        """Record a generated file (absolute, or relative to the project directory)."""
        output = Path(output)
        if output.is_absolute():
            output = output.relative_to(self.project_dir.resolve())
        self.state_dir.mkdir(parents=True, exist_ok=True)
        with open(self.path, "a") as fh:
            fh.write(f"{output.as_posix()}\n")

    def outputs(self) -> list[Path]:
        """Recorded outputs as paths under the project directory, deduplicated, in order."""
        if not self.exists():
            return []
        lines = (line.strip() for line in self.path.read_text().splitlines())
        return [self.project_dir / p for p in dict.fromkeys(lines) if p]